# https://pre-commit.com/
ci:
    # The repos are quite stable and doesn't effectively change the code that
    # often. So no need for the bot to update the rev that often.
    autoupdate_schedule: quarterly

# Dont format test dcm-files at all as they contain typical errors that the
# parser has to handle.
exclude: "tests/Sample.dcm"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: mixed-line-ending
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
        name: absolufy-imports
        files: ^src/dcmReader/
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.235'
    hooks:
      - id: ruff
        args: ["--fix"]
  # https://github.com/python/black#version-control-integration
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
      - id: black-jupyter
  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.8
    hooks:
      - id: blackdoc
        additional_dependencies: ["black==22.12.0"]
      - id: blackdoc-autoupdate-black
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        # This is slow and so we take it out of the fast-path; requires passing
        # `--hook-stage manual` to pre-commit
        stages: [manual]
        additional_dependencies: [
            # Type stubs
            types-python-dateutil,
            types-pkg_resources,
            types-PyYAML,
            types-pytz,
            typing-extensions,
          ]
